/*
RegExp which was used to generate this api:
input: all names from the ws api as list
search: (\w+)
replace: \U$1\E {\n name:"$1",\n args:{},\n restrictedToLoggedIn: false, \n callableFromAjax: false, \n },
 */

export const Services_3_2 = {

	version: "3.2",

	URL_WS: "webservice/rest/server.php",

	URL_TOKEN: "login/token.php",

	AUTH_GET_TOKEN: {
		name: "",
		description: "Default service for login.",
		args: function(username, password, resultformat = 'json'){
			return {
				username: username,
				password: password,
				service: "moodle_mobile_app",
				moodlewsrestformat: resultformat,
			}
		},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},

	////////////////////////////////////////////////////////////////////////////////////////

	AUTH_EMAIL_GET_SIGNUP_SETTINGS: {
		name: "auth_email_get_signup_settings",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	AUTH_EMAIL_SIGNUP_USER: {
		name: "auth_email_signup_user",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_AUTH_CONFIRM_USER: {
		name: "core_auth_confirm_user",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_BADGES_GET_USER_BADGES: {
		name: "core_badges_get_user_badges",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_CALENDAR_CREATE_CALENDAR_EVENTS: {
		name: "core_calendar_create_calendar_events",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_CALENDAR_DELETE_CALENDAR_EVENTS: {
		name: "core_calendar_delete_calendar_events",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_CALENDAR_GET_CALENDAR_EVENTS: {
		name: "core_calendar_get_calendar_events",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COHORT_ADD_COHORT_MEMBERS: {
		name: "core_cohort_add_cohort_members",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COHORT_CREATE_COHORTS: {
		name: "core_cohort_create_cohorts",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COHORT_DELETE_COHORTS: {
		name: "core_cohort_delete_cohorts",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COHORT_DELETE_COHORT_MEMBERS: {
		name: "core_cohort_delete_cohort_members",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COHORT_GET_COHORTS: {
		name: "core_cohort_get_cohorts",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COHORT_GET_COHORT_MEMBERS: {
		name: "core_cohort_get_cohort_members",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COHORT_UPDATE_COHORTS: {
		name: "core_cohort_update_cohorts",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMMENT_GET_COMMENTS: {
		name: "core_comment_get_comments",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_ADD_COMPETENCY_TO_COURSE: {
		name: "core_competency_add_competency_to_course",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_ADD_COMPETENCY_TO_PLAN: {
		name: "core_competency_add_competency_to_plan",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_ADD_COMPETENCY_TO_TEMPLATE: {
		name: "core_competency_add_competency_to_template",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_ADD_RELATED_COMPETENCY: {
		name: "core_competency_add_related_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_APPROVE_PLAN: {
		name: "core_competency_approve_plan",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_COMPETENCY_FRAMEWORK_VIEWED: {
		name: "core_competency_competency_framework_viewed",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_COMPETENCY_VIEWED: {
		name: "core_competency_competency_viewed",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_COMPLETE_PLAN: {
		name: "core_competency_complete_plan",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_COUNT_COMPETENCIES: {
		name: "core_competency_count_competencies",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_COUNT_COMPETENCIES_IN_COURSE: {
		name: "core_competency_count_competencies_in_course",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_COUNT_COMPETENCIES_IN_TEMPLATE: {
		name: "core_competency_count_competencies_in_template",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_COUNT_COMPETENCY_FRAMEWORKS: {
		name: "core_competency_count_competency_frameworks",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_COUNT_COURSES_USING_COMPETENCY: {
		name: "core_competency_count_courses_using_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_COUNT_TEMPLATES: {
		name: "core_competency_count_templates",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_COUNT_TEMPLATES_USING_COMPETENCY: {
		name: "core_competency_count_templates_using_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_CREATE_COMPETENCY: {
		name: "core_competency_create_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_CREATE_COMPETENCY_FRAMEWORK: {
		name: "core_competency_create_competency_framework",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_CREATE_PLAN: {
		name: "core_competency_create_plan",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_CREATE_TEMPLATE: {
		name: "core_competency_create_template",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_CREATE_USER_EVIDENCE_COMPETENCY: {
		name: "core_competency_create_user_evidence_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_DELETE_COMPETENCY: {
		name: "core_competency_delete_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_DELETE_COMPETENCY_FRAMEWORK: {
		name: "core_competency_delete_competency_framework",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_DELETE_EVIDENCE: {
		name: "core_competency_delete_evidence",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_DELETE_PLAN: {
		name: "core_competency_delete_plan",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_DELETE_TEMPLATE: {
		name: "core_competency_delete_template",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_DELETE_USER_EVIDENCE: {
		name: "core_competency_delete_user_evidence",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_DELETE_USER_EVIDENCE_COMPETENCY: {
		name: "core_competency_delete_user_evidence_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_DUPLICATE_COMPETENCY_FRAMEWORK: {
		name: "core_competency_duplicate_competency_framework",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_DUPLICATE_TEMPLATE: {
		name: "core_competency_duplicate_template",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_GET_SCALE_VALUES: {
		name: "core_competency_get_scale_values",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_GRADE_COMPETENCY: {
		name: "core_competency_grade_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_GRADE_COMPETENCY_IN_COURSE: {
		name: "core_competency_grade_competency_in_course",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_GRADE_COMPETENCY_IN_PLAN: {
		name: "core_competency_grade_competency_in_plan",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_LIST_COMPETENCIES: {
		name: "core_competency_list_competencies",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_LIST_COMPETENCIES_IN_TEMPLATE: {
		name: "core_competency_list_competencies_in_template",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_LIST_COMPETENCY_FRAMEWORKS: {
		name: "core_competency_list_competency_frameworks",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_LIST_COURSE_COMPETENCIES: {
		name: "core_competency_list_course_competencies",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_LIST_PLAN_COMPETENCIES: {
		name: "core_competency_list_plan_competencies",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_LIST_TEMPLATES: {
		name: "core_competency_list_templates",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_LIST_TEMPLATES_USING_COMPETENCY: {
		name: "core_competency_list_templates_using_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_LIST_USER_PLANS: {
		name: "core_competency_list_user_plans",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_MOVE_DOWN_COMPETENCY: {
		name: "core_competency_move_down_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_MOVE_UP_COMPETENCY: {
		name: "core_competency_move_up_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_PLAN_CANCEL_REVIEW_REQUEST: {
		name: "core_competency_plan_cancel_review_request",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_PLAN_REQUEST_REVIEW: {
		name: "core_competency_plan_request_review",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_PLAN_START_REVIEW: {
		name: "core_competency_plan_start_review",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_PLAN_STOP_REVIEW: {
		name: "core_competency_plan_stop_review",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_READ_COMPETENCY: {
		name: "core_competency_read_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_READ_COMPETENCY_FRAMEWORK: {
		name: "core_competency_read_competency_framework",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_READ_PLAN: {
		name: "core_competency_read_plan",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_READ_TEMPLATE: {
		name: "core_competency_read_template",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_READ_USER_EVIDENCE: {
		name: "core_competency_read_user_evidence",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_REMOVE_COMPETENCY_FROM_COURSE: {
		name: "core_competency_remove_competency_from_course",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_REMOVE_COMPETENCY_FROM_PLAN: {
		name: "core_competency_remove_competency_from_plan",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_REMOVE_COMPETENCY_FROM_TEMPLATE: {
		name: "core_competency_remove_competency_from_template",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_REMOVE_RELATED_COMPETENCY: {
		name: "core_competency_remove_related_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_REOPEN_PLAN: {
		name: "core_competency_reopen_plan",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_REORDER_COURSE_COMPETENCY: {
		name: "core_competency_reorder_course_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_REORDER_PLAN_COMPETENCY: {
		name: "core_competency_reorder_plan_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_REORDER_TEMPLATE_COMPETENCY: {
		name: "core_competency_reorder_template_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_REQUEST_REVIEW_OF_USER_EVIDENCE_LINKED_COMPETENCIES: {
		name: "core_competency_request_review_of_user_evidence_linked_competencies",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_SEARCH_COMPETENCIES: {
		name: "core_competency_search_competencies",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_SET_COURSE_COMPETENCY_RULEOUTCOME: {
		name: "core_competency_set_course_competency_ruleoutcome",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_SET_PARENT_COMPETENCY: {
		name: "core_competency_set_parent_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_TEMPLATE_HAS_RELATED_DATA: {
		name: "core_competency_template_has_related_data",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_TEMPLATE_VIEWED: {
		name: "core_competency_template_viewed",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_UNAPPROVE_PLAN: {
		name: "core_competency_unapprove_plan",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_UNLINK_PLAN_FROM_TEMPLATE: {
		name: "core_competency_unlink_plan_from_template",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_UPDATE_COMPETENCY: {
		name: "core_competency_update_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_UPDATE_COMPETENCY_FRAMEWORK: {
		name: "core_competency_update_competency_framework",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_UPDATE_COURSE_COMPETENCY_SETTINGS: {
		name: "core_competency_update_course_competency_settings",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_UPDATE_PLAN: {
		name: "core_competency_update_plan",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_UPDATE_TEMPLATE: {
		name: "core_competency_update_template",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_USER_COMPETENCY_CANCEL_REVIEW_REQUEST: {
		name: "core_competency_user_competency_cancel_review_request",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_USER_COMPETENCY_PLAN_VIEWED: {
		name: "core_competency_user_competency_plan_viewed",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_USER_COMPETENCY_REQUEST_REVIEW: {
		name: "core_competency_user_competency_request_review",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_USER_COMPETENCY_START_REVIEW: {
		name: "core_competency_user_competency_start_review",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_USER_COMPETENCY_STOP_REVIEW: {
		name: "core_competency_user_competency_stop_review",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_USER_COMPETENCY_VIEWED: {
		name: "core_competency_user_competency_viewed",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_USER_COMPETENCY_VIEWED_IN_COURSE: {
		name: "core_competency_user_competency_viewed_in_course",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPETENCY_USER_COMPETENCY_VIEWED_IN_PLAN: {
		name: "core_competency_user_competency_viewed_in_plan",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPLETION_GET_ACTIVITIES_COMPLETION_STATUS: {
		name: "core_completion_get_activities_completion_status",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPLETION_GET_COURSE_COMPLETION_STATUS: {
		name: "core_completion_get_course_completion_status",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPLETION_MARK_COURSE_SELF_COMPLETED: {
		name: "core_completion_mark_course_self_completed",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COMPLETION_UPDATE_ACTIVITY_COMPLETION_STATUS_MANUALLY: {
		name: "core_completion_update_activity_completion_status_manually",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_CHECK_UPDATES: {
		name: "core_course_check_updates",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_CREATE_CATEGORIES: {
		name: "core_course_create_categories",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_CREATE_COURSES: {
		name: "core_course_create_courses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_DELETE_CATEGORIES: {
		name: "core_course_delete_categories",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_DELETE_COURSES: {
		name: "core_course_delete_courses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_DELETE_MODULES: {
		name: "core_course_delete_modules",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_DUPLICATE_COURSE: {
		name: "core_course_duplicate_course",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_GET_ACTIVITIES_OVERVIEW: {
		name: "core_course_get_activities_overview",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_GET_CATEGORIES: {
		name: "core_course_get_categories",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_GET_CONTENTS: {
		name: "core_course_get_contents",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_GET_COURSES: {
		name: "core_course_get_courses",
		description: "Return course details",
		requiredCapabilities: [
			'moodle/course:view',
			'moodle/course:update',
			'moodle/course:viewhiddencourses'
		],
		args: function(token, optionalIds=[], wsRestFormat = 'json'){
			return {
				wsfunction: "core_course_get_courses",
				wstoken: token,
				ids: optionalIds,
				moodlewsrestformat: wsRestFormat,
			}
		},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_GET_COURSES_BY_FIELD: {
		name: "core_course_get_courses_by_field",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_GET_COURSE_MODULE: {
		name: "core_course_get_course_module",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_GET_COURSE_MODULE_BY_INSTANCE: {
		name: "core_course_get_course_module_by_instance",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_GET_USER_ADMINISTRATION_OPTIONS: {
		name: "core_course_get_user_administration_options",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_GET_USER_NAVIGATION_OPTIONS: {
		name: "core_course_get_user_navigation_options",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_IMPORT_COURSE: {
		name: "core_course_import_course",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_SEARCH_COURSES: {
		name: "core_course_search_courses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_UPDATE_CATEGORIES: {
		name: "core_course_update_categories",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_UPDATE_COURSES: {
		name: "core_course_update_courses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_COURSE_VIEW_COURSE: {
		name: "core_course_view_course",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_ENROL_GET_COURSE_ENROLMENT_METHODS: {
		name: "core_enrol_get_course_enrolment_methods",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_ENROL_GET_ENROLLED_USERS: {
		name: "core_enrol_get_enrolled_users",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_ENROL_GET_ENROLLED_USERS_WITH_CAPABILITY: {
		name: "core_enrol_get_enrolled_users_with_capability",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_ENROL_GET_USERS_COURSES: {
		name: "core_enrol_get_users_courses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_FETCH_NOTIFICATIONS: {
		name: "core_fetch_notifications",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_FILES_GET_FILES: {
		name: "core_files_get_files",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_FILES_UPLOAD: {
		name: "core_files_upload",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GET_COMPONENT_STRINGS: {
		name: "core_get_component_strings",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GET_FRAGMENT: {
		name: "core_get_fragment",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GET_STRING: {
		name: "core_get_string",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GET_STRINGS: {
		name: "core_get_strings",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GRADES_GET_GRADES: {
		name: "core_grades_get_grades",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GRADES_UPDATE_GRADES: {
		name: "core_grades_update_grades",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GRADING_GET_DEFINITIONS: {
		name: "core_grading_get_definitions",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GRADING_GET_GRADINGFORM_INSTANCES: {
		name: "core_grading_get_gradingform_instances",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GRADING_SAVE_DEFINITIONS: {
		name: "core_grading_save_definitions",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GROUP_ADD_GROUP_MEMBERS: {
		name: "core_group_add_group_members",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GROUP_ASSIGN_GROUPING: {
		name: "core_group_assign_grouping",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GROUP_CREATE_GROUPINGS: {
		name: "core_group_create_groupings",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GROUP_CREATE_GROUPS: {
		name: "core_group_create_groups",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GROUP_DELETE_GROUPINGS: {
		name: "core_group_delete_groupings",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GROUP_DELETE_GROUPS: {
		name: "core_group_delete_groups",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GROUP_DELETE_GROUP_MEMBERS: {
		name: "core_group_delete_group_members",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GROUP_GET_ACTIVITY_ALLOWED_GROUPS: {
		name: "core_group_get_activity_allowed_groups",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GROUP_GET_ACTIVITY_GROUPMODE: {
		name: "core_group_get_activity_groupmode",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GROUP_GET_COURSE_GROUPINGS: {
		name: "core_group_get_course_groupings",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GROUP_GET_COURSE_GROUPS: {
		name: "core_group_get_course_groups",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GROUP_GET_COURSE_USER_GROUPS: {
		name: "core_group_get_course_user_groups",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GROUP_GET_GROUPINGS: {
		name: "core_group_get_groupings",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GROUP_GET_GROUPS: {
		name: "core_group_get_groups",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GROUP_GET_GROUP_MEMBERS: {
		name: "core_group_get_group_members",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GROUP_UNASSIGN_GROUPING: {
		name: "core_group_unassign_grouping",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_GROUP_UPDATE_GROUPINGS: {
		name: "core_group_update_groupings",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_BLOCK_CONTACTS: {
		name: "core_message_block_contacts",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_CREATE_CONTACTS: {
		name: "core_message_create_contacts",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_DATA_FOR_MESSAGEAREA_CONTACTS: {
		name: "core_message_data_for_messagearea_contacts",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_DATA_FOR_MESSAGEAREA_CONVERSATIONS: {
		name: "core_message_data_for_messagearea_conversations",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_DATA_FOR_MESSAGEAREA_GET_MOST_RECENT_MESSAGE: {
		name: "core_message_data_for_messagearea_get_most_recent_message",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_DATA_FOR_MESSAGEAREA_GET_PROFILE: {
		name: "core_message_data_for_messagearea_get_profile",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_DATA_FOR_MESSAGEAREA_MESSAGES: {
		name: "core_message_data_for_messagearea_messages",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_DATA_FOR_MESSAGEAREA_SEARCH_MESSAGES: {
		name: "core_message_data_for_messagearea_search_messages",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_DATA_FOR_MESSAGEAREA_SEARCH_USERS: {
		name: "core_message_data_for_messagearea_search_users",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_DATA_FOR_MESSAGEAREA_SEARCH_USERS_IN_COURSE: {
		name: "core_message_data_for_messagearea_search_users_in_course",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_DELETE_CONTACTS: {
		name: "core_message_delete_contacts",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_DELETE_CONVERSATION: {
		name: "core_message_delete_conversation",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_DELETE_MESSAGE: {
		name: "core_message_delete_message",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_GET_BLOCKED_USERS: {
		name: "core_message_get_blocked_users",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_GET_CONTACTS: {
		name: "core_message_get_contacts",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_GET_MESSAGES: {
		name: "core_message_get_messages",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_GET_MESSAGE_PROCESSOR: {
		name: "core_message_get_message_processor",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_GET_UNREAD_CONVERSATIONS_COUNT: {
		name: "core_message_get_unread_conversations_count",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_GET_USER_MESSAGE_PREFERENCES: {
		name: "core_message_get_user_message_preferences",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_GET_USER_NOTIFICATION_PREFERENCES: {
		name: "core_message_get_user_notification_preferences",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_MARK_ALL_MESSAGES_AS_READ: {
		name: "core_message_mark_all_messages_as_read",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_MARK_ALL_NOTIFICATIONS_AS_READ: {
		name: "core_message_mark_all_notifications_as_read",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_MARK_MESSAGE_READ: {
		name: "core_message_mark_message_read",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_MESSAGE_PROCESSOR_CONFIG_FORM: {
		name: "core_message_message_processor_config_form",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_SEARCH_CONTACTS: {
		name: "core_message_search_contacts",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_SEND_INSTANT_MESSAGES: {
		name: "core_message_send_instant_messages",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_MESSAGE_UNBLOCK_CONTACTS: {
		name: "core_message_unblock_contacts",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_NOTES_CREATE_NOTES: {
		name: "core_notes_create_notes",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_NOTES_DELETE_NOTES: {
		name: "core_notes_delete_notes",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_NOTES_GET_COURSE_NOTES: {
		name: "core_notes_get_course_notes",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_NOTES_GET_NOTES: {
		name: "core_notes_get_notes",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_NOTES_UPDATE_NOTES: {
		name: "core_notes_update_notes",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_NOTES_VIEW_NOTES: {
		name: "core_notes_view_notes",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_OUTPUT_LOAD_TEMPLATE: {
		name: "core_output_load_template",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_QUESTION_UPDATE_FLAG: {
		name: "core_question_update_flag",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_RATING_ADD_RATING: {
		name: "core_rating_add_rating",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_RATING_GET_ITEM_RATINGS: {
		name: "core_rating_get_item_ratings",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_ROLE_ASSIGN_ROLES: {
		name: "core_role_assign_roles",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_ROLE_UNASSIGN_ROLES: {
		name: "core_role_unassign_roles",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_TAG_GET_TAGINDEX: {
		name: "core_tag_get_tagindex",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_TAG_GET_TAGS: {
		name: "core_tag_get_tags",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_TAG_UPDATE_TAGS: {
		name: "core_tag_update_tags",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_UPDATE_INPLACE_EDITABLE: {
		name: "core_update_inplace_editable",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_USER_ADD_USER_DEVICE: {
		name: "core_user_add_user_device",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_USER_ADD_USER_PRIVATE_FILES: {
		name: "core_user_add_user_private_files",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_USER_AGREE_SITE_POLICY: {
		name: "core_user_agree_site_policy",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_USER_CREATE_USERS: {
		name: "core_user_create_users",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_USER_DELETE_USERS: {
		name: "core_user_delete_users",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_USER_GET_COURSE_USER_PROFILES: {
		name: "core_user_get_course_user_profiles",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_USER_GET_USERS: {
		name: "core_user_get_users",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_USER_GET_USERS_BY_FIELD: {
		name: "core_user_get_users_by_field",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_USER_GET_USER_PREFERENCES: {
		name: "core_user_get_user_preferences",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_USER_REMOVE_USER_DEVICE: {
		name: "core_user_remove_user_device",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_USER_SET_USER_PREFERENCES: {
		name: "core_user_set_user_preferences",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_USER_UPDATE_PICTURE: {
		name: "core_user_update_picture",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_USER_UPDATE_USERS: {
		name: "core_user_update_users",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_USER_UPDATE_USER_PREFERENCES: {
		name: "core_user_update_user_preferences",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_USER_VIEW_USER_LIST: {
		name: "core_user_view_user_list",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_USER_VIEW_USER_PROFILE: {
		name: "core_user_view_user_profile",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	CORE_WEBSERVICE_GET_SITE_INFO: {
		name: "core_webservice_get_site_info",
		description: "Return some site info / user info / list web service functions",
		requiredCapabilities: [],
		args: function (token, wsRestFormat = 'json') {
			return {
				wsfunction: "core_webservice_get_site_info",
				wstoken: token,
				moodlewsrestformat: wsRestFormat,
			}
		},
		restrictedToLoggedIn: false, 	// TODO: yet unkown, no info in the api documentation,
		callableFromAjax: false,		// TODO: yet unkown, no info in the api documentation
	},
	ENROL_GUEST_GET_INSTANCE_INFO: {
		name: "enrol_guest_get_instance_info",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	ENROL_MANUAL_ENROL_USERS: {
		name: "enrol_manual_enrol_users",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	ENROL_MANUAL_UNENROL_USERS: {
		name: "enrol_manual_unenrol_users",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	ENROL_SELF_ENROL_USER: {
		name: "enrol_self_enrol_user",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	ENROL_SELF_GET_INSTANCE_INFO: {
		name: "enrol_self_get_instance_info",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	GRADEREPORT_OVERVIEW_GET_COURSE_GRADES: {
		name: "gradereport_overview_get_course_grades",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	GRADEREPORT_OVERVIEW_VIEW_GRADE_REPORT: {
		name: "gradereport_overview_view_grade_report",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	GRADEREPORT_USER_GET_GRADES_TABLE: {
		name: "gradereport_user_get_grades_table",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	GRADEREPORT_USER_GET_GRADE_ITEMS: {
		name: "gradereport_user_get_grade_items",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	GRADEREPORT_USER_VIEW_GRADE_REPORT: {
		name: "gradereport_user_view_grade_report",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MESSAGE_AIRNOTIFIER_ARE_NOTIFICATION_PREFERENCES_CONFIGURED: {
		name: "message_airnotifier_are_notification_preferences_configured",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MESSAGE_AIRNOTIFIER_ENABLE_DEVICE: {
		name: "message_airnotifier_enable_device",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MESSAGE_AIRNOTIFIER_GET_USER_DEVICES: {
		name: "message_airnotifier_get_user_devices",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MESSAGE_AIRNOTIFIER_IS_SYSTEM_CONFIGURED: {
		name: "message_airnotifier_is_system_configured",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MESSAGE_POPUP_GET_POPUP_NOTIFICATIONS: {
		name: "message_popup_get_popup_notifications",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MESSAGE_POPUP_GET_UNREAD_POPUP_NOTIFICATION_COUNT: {
		name: "message_popup_get_unread_popup_notification_count",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_COPY_PREVIOUS_ATTEMPT: {
		name: "mod_assign_copy_previous_attempt",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_GET_ASSIGNMENTS: {
		name: "mod_assign_get_assignments",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_GET_GRADES: {
		name: "mod_assign_get_grades",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_GET_PARTICIPANT: {
		name: "mod_assign_get_participant",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_GET_SUBMISSIONS: {
		name: "mod_assign_get_submissions",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_GET_SUBMISSION_STATUS: {
		name: "mod_assign_get_submission_status",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_GET_USER_FLAGS: {
		name: "mod_assign_get_user_flags",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_GET_USER_MAPPINGS: {
		name: "mod_assign_get_user_mappings",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_LIST_PARTICIPANTS: {
		name: "mod_assign_list_participants",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_LOCK_SUBMISSIONS: {
		name: "mod_assign_lock_submissions",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_REVEAL_IDENTITIES: {
		name: "mod_assign_reveal_identities",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_REVERT_SUBMISSIONS_TO_DRAFT: {
		name: "mod_assign_revert_submissions_to_draft",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_SAVE_GRADE: {
		name: "mod_assign_save_grade",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_SAVE_GRADES: {
		name: "mod_assign_save_grades",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_SAVE_SUBMISSION: {
		name: "mod_assign_save_submission",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_SAVE_USER_EXTENSIONS: {
		name: "mod_assign_save_user_extensions",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_SET_USER_FLAGS: {
		name: "mod_assign_set_user_flags",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_SUBMIT_FOR_GRADING: {
		name: "mod_assign_submit_for_grading",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_SUBMIT_GRADING_FORM: {
		name: "mod_assign_submit_grading_form",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_UNLOCK_SUBMISSIONS: {
		name: "mod_assign_unlock_submissions",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_VIEW_ASSIGN: {
		name: "mod_assign_view_assign",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_VIEW_GRADING_TABLE: {
		name: "mod_assign_view_grading_table",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_ASSIGN_VIEW_SUBMISSION_STATUS: {
		name: "mod_assign_view_submission_status",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_BOOK_GET_BOOKS_BY_COURSES: {
		name: "mod_book_get_books_by_courses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_BOOK_VIEW_BOOK: {
		name: "mod_book_view_book",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_CHAT_GET_CHATS_BY_COURSES: {
		name: "mod_chat_get_chats_by_courses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_CHAT_GET_CHAT_LATEST_MESSAGES: {
		name: "mod_chat_get_chat_latest_messages",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_CHAT_GET_CHAT_USERS: {
		name: "mod_chat_get_chat_users",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_CHAT_LOGIN_USER: {
		name: "mod_chat_login_user",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_CHAT_SEND_CHAT_MESSAGE: {
		name: "mod_chat_send_chat_message",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_CHAT_VIEW_CHAT: {
		name: "mod_chat_view_chat",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_CHOICE_DELETE_CHOICE_RESPONSES: {
		name: "mod_choice_delete_choice_responses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_CHOICE_GET_CHOICES_BY_COURSES: {
		name: "mod_choice_get_choices_by_courses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_CHOICE_GET_CHOICE_OPTIONS: {
		name: "mod_choice_get_choice_options",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_CHOICE_GET_CHOICE_RESULTS: {
		name: "mod_choice_get_choice_results",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_CHOICE_SUBMIT_CHOICE_RESPONSE: {
		name: "mod_choice_submit_choice_response",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_CHOICE_VIEW_CHOICE: {
		name: "mod_choice_view_choice",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_DATA_GET_DATABASES_BY_COURSES: {
		name: "mod_data_get_databases_by_courses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_FOLDER_VIEW_FOLDER: {
		name: "mod_folder_view_folder",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_FORUM_ADD_DISCUSSION: {
		name: "mod_forum_add_discussion",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_FORUM_ADD_DISCUSSION_POST: {
		name: "mod_forum_add_discussion_post",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_FORUM_CAN_ADD_DISCUSSION: {
		name: "mod_forum_can_add_discussion",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_FORUM_GET_FORUMS_BY_COURSES: {
		name: "mod_forum_get_forums_by_courses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_FORUM_GET_FORUM_DISCUSSIONS_PAGINATED: {
		name: "mod_forum_get_forum_discussions_paginated",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_FORUM_GET_FORUM_DISCUSSION_POSTS: {
		name: "mod_forum_get_forum_discussion_posts",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_FORUM_VIEW_FORUM: {
		name: "mod_forum_view_forum",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_FORUM_VIEW_FORUM_DISCUSSION: {
		name: "mod_forum_view_forum_discussion",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_GLOSSARY_ADD_ENTRY: {
		name: "mod_glossary_add_entry",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_GLOSSARY_GET_AUTHORS: {
		name: "mod_glossary_get_authors",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_GLOSSARY_GET_CATEGORIES: {
		name: "mod_glossary_get_categories",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_GLOSSARY_GET_ENTRIES_BY_AUTHOR: {
		name: "mod_glossary_get_entries_by_author",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_GLOSSARY_GET_ENTRIES_BY_AUTHOR_ID: {
		name: "mod_glossary_get_entries_by_author_id",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_GLOSSARY_GET_ENTRIES_BY_CATEGORY: {
		name: "mod_glossary_get_entries_by_category",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_GLOSSARY_GET_ENTRIES_BY_DATE: {
		name: "mod_glossary_get_entries_by_date",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_GLOSSARY_GET_ENTRIES_BY_LETTER: {
		name: "mod_glossary_get_entries_by_letter",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_GLOSSARY_GET_ENTRIES_BY_SEARCH: {
		name: "mod_glossary_get_entries_by_search",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_GLOSSARY_GET_ENTRIES_BY_TERM: {
		name: "mod_glossary_get_entries_by_term",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_GLOSSARY_GET_ENTRIES_TO_APPROVE: {
		name: "mod_glossary_get_entries_to_approve",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_GLOSSARY_GET_ENTRY_BY_ID: {
		name: "mod_glossary_get_entry_by_id",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_GLOSSARY_GET_GLOSSARIES_BY_COURSES: {
		name: "mod_glossary_get_glossaries_by_courses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_GLOSSARY_VIEW_ENTRY: {
		name: "mod_glossary_view_entry",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_GLOSSARY_VIEW_GLOSSARY: {
		name: "mod_glossary_view_glossary",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_IMSCP_GET_IMSCPS_BY_COURSES: {
		name: "mod_imscp_get_imscps_by_courses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_IMSCP_VIEW_IMSCP: {
		name: "mod_imscp_view_imscp",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_LTI_CREATE_TOOL_PROXY: {
		name: "mod_lti_create_tool_proxy",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_LTI_CREATE_TOOL_TYPE: {
		name: "mod_lti_create_tool_type",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_LTI_DELETE_TOOL_PROXY: {
		name: "mod_lti_delete_tool_proxy",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_LTI_DELETE_TOOL_TYPE: {
		name: "mod_lti_delete_tool_type",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_LTI_GET_LTIS_BY_COURSES: {
		name: "mod_lti_get_ltis_by_courses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_LTI_GET_TOOL_LAUNCH_DATA: {
		name: "mod_lti_get_tool_launch_data",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_LTI_GET_TOOL_PROXIES: {
		name: "mod_lti_get_tool_proxies",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_LTI_GET_TOOL_PROXY_REGISTRATION_REQUEST: {
		name: "mod_lti_get_tool_proxy_registration_request",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_LTI_GET_TOOL_TYPES: {
		name: "mod_lti_get_tool_types",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_LTI_IS_CARTRIDGE: {
		name: "mod_lti_is_cartridge",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_LTI_UPDATE_TOOL_TYPE: {
		name: "mod_lti_update_tool_type",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_LTI_VIEW_LTI: {
		name: "mod_lti_view_lti",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_PAGE_VIEW_PAGE: {
		name: "mod_page_view_page",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_GET_ATTEMPT_ACCESS_INFORMATION: {
		name: "mod_quiz_get_attempt_access_information",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_GET_ATTEMPT_DATA: {
		name: "mod_quiz_get_attempt_data",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_GET_ATTEMPT_REVIEW: {
		name: "mod_quiz_get_attempt_review",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_GET_ATTEMPT_SUMMARY: {
		name: "mod_quiz_get_attempt_summary",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_GET_COMBINED_REVIEW_OPTIONS: {
		name: "mod_quiz_get_combined_review_options",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_GET_QUIZZES_BY_COURSES: {
		name: "mod_quiz_get_quizzes_by_courses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_GET_QUIZ_ACCESS_INFORMATION: {
		name: "mod_quiz_get_quiz_access_information",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_GET_QUIZ_FEEDBACK_FOR_GRADE: {
		name: "mod_quiz_get_quiz_feedback_for_grade",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_GET_QUIZ_REQUIRED_QTYPES: {
		name: "mod_quiz_get_quiz_required_qtypes",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_GET_USER_ATTEMPTS: {
		name: "mod_quiz_get_user_attempts",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_GET_USER_BEST_GRADE: {
		name: "mod_quiz_get_user_best_grade",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_PROCESS_ATTEMPT: {
		name: "mod_quiz_process_attempt",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_SAVE_ATTEMPT: {
		name: "mod_quiz_save_attempt",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_START_ATTEMPT: {
		name: "mod_quiz_start_attempt",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_VIEW_ATTEMPT: {
		name: "mod_quiz_view_attempt",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_VIEW_ATTEMPT_REVIEW: {
		name: "mod_quiz_view_attempt_review",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_VIEW_ATTEMPT_SUMMARY: {
		name: "mod_quiz_view_attempt_summary",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_QUIZ_VIEW_QUIZ: {
		name: "mod_quiz_view_quiz",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_RESOURCE_VIEW_RESOURCE: {
		name: "mod_resource_view_resource",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_SCORM_GET_SCORMS_BY_COURSES: {
		name: "mod_scorm_get_scorms_by_courses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_SCORM_GET_SCORM_ATTEMPT_COUNT: {
		name: "mod_scorm_get_scorm_attempt_count",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_SCORM_GET_SCORM_SCOES: {
		name: "mod_scorm_get_scorm_scoes",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_SCORM_GET_SCORM_SCO_TRACKS: {
		name: "mod_scorm_get_scorm_sco_tracks",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_SCORM_GET_SCORM_USER_DATA: {
		name: "mod_scorm_get_scorm_user_data",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_SCORM_INSERT_SCORM_TRACKS: {
		name: "mod_scorm_insert_scorm_tracks",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_SCORM_LAUNCH_SCO: {
		name: "mod_scorm_launch_sco",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_SCORM_VIEW_SCORM: {
		name: "mod_scorm_view_scorm",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_SURVEY_GET_QUESTIONS: {
		name: "mod_survey_get_questions",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_SURVEY_GET_SURVEYS_BY_COURSES: {
		name: "mod_survey_get_surveys_by_courses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_SURVEY_SUBMIT_ANSWERS: {
		name: "mod_survey_submit_answers",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_SURVEY_VIEW_SURVEY: {
		name: "mod_survey_view_survey",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_URL_VIEW_URL: {
		name: "mod_url_view_url",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_WIKI_EDIT_PAGE: {
		name: "mod_wiki_edit_page",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_WIKI_GET_PAGE_CONTENTS: {
		name: "mod_wiki_get_page_contents",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_WIKI_GET_PAGE_FOR_EDITING: {
		name: "mod_wiki_get_page_for_editing",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_WIKI_GET_SUBWIKIS: {
		name: "mod_wiki_get_subwikis",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_WIKI_GET_SUBWIKI_FILES: {
		name: "mod_wiki_get_subwiki_files",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_WIKI_GET_SUBWIKI_PAGES: {
		name: "mod_wiki_get_subwiki_pages",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_WIKI_GET_WIKIS_BY_COURSES: {
		name: "mod_wiki_get_wikis_by_courses",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_WIKI_NEW_PAGE: {
		name: "mod_wiki_new_page",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_WIKI_VIEW_PAGE: {
		name: "mod_wiki_view_page",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	MOD_WIKI_VIEW_WIKI: {
		name: "mod_wiki_view_wiki",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	REPORT_COMPETENCY_DATA_FOR_REPORT: {
		name: "report_competency_data_for_report",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_LP_DATA_FOR_COMPETENCIES_MANAGE_PAGE: {
		name: "tool_lp_data_for_competencies_manage_page",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_LP_DATA_FOR_COMPETENCY_FRAMEWORKS_MANAGE_PAGE: {
		name: "tool_lp_data_for_competency_frameworks_manage_page",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_LP_DATA_FOR_COMPETENCY_SUMMARY: {
		name: "tool_lp_data_for_competency_summary",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_LP_DATA_FOR_COURSE_COMPETENCIES_PAGE: {
		name: "tool_lp_data_for_course_competencies_page",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_LP_DATA_FOR_PLANS_PAGE: {
		name: "tool_lp_data_for_plans_page",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_LP_DATA_FOR_PLAN_PAGE: {
		name: "tool_lp_data_for_plan_page",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_LP_DATA_FOR_RELATED_COMPETENCIES_SECTION: {
		name: "tool_lp_data_for_related_competencies_section",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_LP_DATA_FOR_TEMPLATES_MANAGE_PAGE: {
		name: "tool_lp_data_for_templates_manage_page",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_LP_DATA_FOR_TEMPLATE_COMPETENCIES_PAGE: {
		name: "tool_lp_data_for_template_competencies_page",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_LP_DATA_FOR_USER_COMPETENCY_SUMMARY: {
		name: "tool_lp_data_for_user_competency_summary",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_LP_DATA_FOR_USER_COMPETENCY_SUMMARY_IN_COURSE: {
		name: "tool_lp_data_for_user_competency_summary_in_course",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_LP_DATA_FOR_USER_COMPETENCY_SUMMARY_IN_PLAN: {
		name: "tool_lp_data_for_user_competency_summary_in_plan",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_LP_DATA_FOR_USER_EVIDENCE_LIST_PAGE: {
		name: "tool_lp_data_for_user_evidence_list_page",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_LP_DATA_FOR_USER_EVIDENCE_PAGE: {
		name: "tool_lp_data_for_user_evidence_page",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_LP_LIST_COURSES_USING_COMPETENCY: {
		name: "tool_lp_list_courses_using_competency",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_LP_SEARCH_COHORTS: {
		name: "tool_lp_search_cohorts",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_LP_SEARCH_USERS: {
		name: "tool_lp_search_users",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_MOBILE_GET_AUTOLOGIN_KEY: {
		name: "tool_mobile_get_autologin_key",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_MOBILE_GET_CONFIG: {
		name: "tool_mobile_get_config",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_MOBILE_GET_PLUGINS_SUPPORTING_MOBILE: {
		name: "tool_mobile_get_plugins_supporting_mobile",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_MOBILE_GET_PUBLIC_CONFIG: {
		name: "tool_mobile_get_public_config",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_TEMPLATELIBRARY_LIST_TEMPLATES: {
		name: "tool_templatelibrary_list_templates",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_TEMPLATELIBRARY_LOAD_CANONICAL_TEMPLATE: {
		name: "tool_templatelibrary_load_canonical_template",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_USERTOURS_COMPLETE_TOUR: {
		name: "tool_usertours_complete_tour",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_USERTOURS_FETCH_AND_START_TOUR: {
		name: "tool_usertours_fetch_and_start_tour",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_USERTOURS_RESET_TOUR: {
		name: "tool_usertours_reset_tour",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
	TOOL_USERTOURS_STEP_SHOWN: {
		name: "tool_usertours_step_shown",
		description: "",
		requiredCapabilities: [],
		args: {},
		restrictedToLoggedIn: false,
		callableFromAjax: false,
	},
}



